# Generated by Django 4.1.2 on 2022-12-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='auction/frontend/public/'),
        ),
    ]
