# Generated by Django 4.1.2 on 2022-12-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_bio_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=120),
        ),
    ]
