# Generated by Django 4.1.2 on 2022-12-15 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_answer_question_remove_item_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auction.item'),
        ),
        migrations.AddField(
            model_name='question',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='auction.item'),
        ),
    ]
