# Generated by Django 4.1.2 on 2022-12-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(upload_to='auction/frontend/public/'),
        ),
    ]
